name: learn-github-actions # The name of the job
on: [push] # The triggering event: pushing to any branch
jobs:
  check-bats-version: # a single job called check-bats-version
    runs-on: ubuntu-latest # using the ubuntu-latest container image
    steps:
      - uses: actions/checkout@v3 # git checkout the code of the repository (default to main branch)
      - name: set up python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.7'
      - name: Install dependencies
        run: | 
            python -m pip install --upgrade pip 
            pip install ruff pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .

      # - uses: actions/setup-node@v3 # install node JS
      #   with:
      #     node-version: '14' # pass a value to the node-version argument of the action
      # - run: npm install -g bats # run a script that installs the bats package
      # - run: | # multiline script
      #     echo "testing bats version:" # print a message
      #     bats -v # print the version
